# Generated by Django 5.1.4 on 2024-12-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('department', models.CharField(max_length=100, verbose_name='科室')),
                ('office', models.CharField(max_length=100, verbose_name='办公室')),
                ('office_phone', models.CharField(blank=True, max_length=15, verbose_name='办公电话')),
                ('mobile_phone', models.CharField(blank=True, max_length=15, verbose_name='手机')),
                ('level', models.CharField(choices=[('局长', '局长'), ('副局长', '副局长'), ('科长', '科长'), ('科员', '科员')], max_length=10, verbose_name='级别')),
                ('leader', models.CharField(blank=True, max_length=100, verbose_name='分管领导')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
    ]
