# Generated by Django 5.1.4 on 2024-12-12 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('headers', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file', models.FileField(upload_to='duplicate_results/')),
                ('checked_columns', models.JSONField()),
                ('duplicate_groups', models.IntegerField()),
                ('duplicate_rows', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExcelDuplicate.excelfile')),
            ],
        ),
    ]
